import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';


export interface DRIVER {
 imgsrc: string,
 number: number,
 nationality: string,
 name: string,
 team: string,
 country: string,
 podiums: number,
 points: number,
 gpEntries: number,
 worldChampionships: number,
 highestRaceFinish: string,
 highestGridPosition: number,
 dateOfBirth: string,
 placeOfBirth: string
}

const drivers: DRIVER[] = [
  {imgsrc: 'assets/driver-info/VER.avif', 
  number: 1, 
  nationality: 'assets/countries/Netherlands.webp', 
  name: 'Max Verstappen',
  team: "Red Bull Racing",
  country: "Netherlands",
  podiums: 102,
  points: 2696.5,
  gpEntries: 190 ,
  worldChampionships: 3,
  highestRaceFinish:"1(x58)",
  highestGridPosition: 1 ,
  dateOfBirth: "30/09/1997" ,
  placeOfBirth: "Hasselt, Belgium" 
  },
  {imgsrc: 'assets/driver-info/PER.avif', 
  number: 11, 
  nationality: 'assets/countries/mexico-flag.avif',
  name: "Sergio Perez", 
  team: "Red Bull Racing",
  country: "Mexico",
  podiums: 39,
  points: 1571,
  gpEntries: 263 ,
  worldChampionships: 0,
  highestRaceFinish:"1 (x6)",
  highestGridPosition: 1 ,
  dateOfBirth: "26/01/1990" ,
  placeOfBirth: "Guadalajara, Mexico" 
  },
  {imgsrc: 'assets/driver-info/LEC.avif', 
  number: 16, 
  nationality: 'assets/countries/monaco-flag.avif',
  name: "Charles Leclerc", 
  team: "Ferrari",
  country: "Monaco",
  podiums: 32,
  points: 1150,
  gpEntries: 130 ,
  worldChampionships: 0,
  highestRaceFinish:"1 (x5)",
  highestGridPosition: 1 ,
  dateOfBirth: "16/10/1997" ,
  placeOfBirth: "Monte Carlo, Monaco" 
  },
  {imgsrc: 'assets/driver-info/SAI.avif', 
  number: 55, 
  nationality: 'assets/countries/spain-flag.avif',
  name: "Carlos Sainz", 
  team: "Ferrari",
  country: "Spain",
  podiums: 21,
  points: 1051.5,
  gpEntries: 189 ,
  worldChampionships: 0,
  highestRaceFinish:"1 (x3)",
  highestGridPosition: 1 ,
  dateOfBirth: "01/09/1994" ,
  placeOfBirth: "Madrid, Spain" 
  },
  {imgsrc: 'assets/driver-info/NOR.avif', 
  number: 4, 
  nationality: 'assets/countries/united-kingdom-flag.avif',
  name: "Lando Norris", 
  team: "McLaren",
  country: "Great Britain",
  podiums: 15,
  points: 691,
  gpEntries: 109 ,
  worldChampionships: 0,
  highestRaceFinish:"2 (x8)",
  highestGridPosition: 1 ,
  dateOfBirth: "13/11/1999" ,
  placeOfBirth: "Bristol, England" 
  },
  {imgsrc: 'assets/driver-info/PIA.avif', 
  number: 81, 
  nationality: 'assets/countries/australia-flag.png',
  name: "Oscar Piastri", 
  team: "McLaren",
  country: "Australia",
  podiums: 2,
  points: 135,
  gpEntries: 27 ,
  worldChampionships: 0,
  highestRaceFinish:"2 (x1)",
  highestGridPosition: 2 ,
  dateOfBirth: "06/04/2001" ,
  placeOfBirth: "Melbourne, Victoria" 
  },
  {imgsrc: 'assets/driver-info/RUS.avif', 
  number: 63, 
  nationality: 'assets/countries/united-kingdom-flag.avif',
  name: "George Russell", 
  team: "Mercedes",
  country: "Great Britain",
  podiums: 11,
  points: 502,
  gpEntries: 109 ,
  worldChampionships: 0,
  highestRaceFinish:"1 (x1)",
  highestGridPosition: 1 ,
  dateOfBirth: "15/02/1998" ,
  placeOfBirth: "King's Lynn, England" 
  },
  {imgsrc: 'assets/driver-info/HAM.avif', 
  number: 44, 
  nationality: 'assets/countries/united-kingdom-flag.avif',
  name: "Lewis Hamilton", 
  team: "Mercedes",
  country: "Great Britain",
  podiums: 197,
  points: 4658.5,
  gpEntries: 337,
  worldChampionships: 7,
  highestRaceFinish:"1 (x103)",
  highestGridPosition: 1 ,
  dateOfBirth: "07/01/1985" ,
  placeOfBirth: "Stevenage, England" 
  },
  {imgsrc: 'assets/driver-info/ALO.avif', 
  number: 14, 
  nationality: 'assets/countries/spain-flag.avif',
  name: "Fernando Alonso", 
  team: "Aston Martin",
  country: "Spain",
  podiums: 106,
  points: 2298,
  gpEntries: 385 ,
  worldChampionships: 2,
  highestRaceFinish:"1 (x32)",
  highestGridPosition: 1 ,
  dateOfBirth: "29/07/1981" ,
  placeOfBirth: "Oviedo, Spain" 
  },
  {imgsrc: 'assets/driver-info/STR.webp', 
  number: 18, 
  nationality: 'assets/countries/canada-flag.avif',
  name: "Lance Stroll", 
  team: "Aston Martin",
  country: "Canada",
  podiums: 3,
  points: 277,
  gpEntries: 148,
  worldChampionships: 0,
  highestRaceFinish:"3 (x3)",
  highestGridPosition: 1 ,
  dateOfBirth: "29/10/1998" ,
  placeOfBirth: "Montreal, Canada" 
  },
  {imgsrc: 'assets/driver-info/TSU.avif', 
  number: 22, 
  nationality: 'assets/countries/japan-flag.avif',
  name: "Yuki Tsunoda", 
  team: "RB",
  country: "Japan",
  podiums: 0,
  points: 68,
  gpEntries: 71,
  worldChampionships: 0,
  highestRaceFinish:"4 (x1)",
  highestGridPosition: 6 ,
  dateOfBirth: "11/05/2000" ,
  placeOfBirth: "Sagamihara, Japan" 
  },
  {imgsrc: 'assets/driver-info/RIC.avif', 
  number: 3, 
  nationality: 'assets/countries/australia-flag.png',
  name: "Daniel Ricciardo", 
  team: "RB",
  country: "Australia",
  podiums: 32,
  points: 1317,
  gpEntries: 244 ,
  worldChampionships: 0,
  highestRaceFinish:"1 (x8)",
  highestGridPosition: 1 ,
  dateOfBirth: "01/07/1989" ,
  placeOfBirth: "Perth, Australia" 
  },
  {imgsrc: 'assets/driver-info/HUL.avif', 
  number: 27, 
  nationality: 'assets/countries/germany-flag.avif',
  name: "Nico Hulkenberg", 
  team: "Haas",
  country: "Germany",
  podiums: 0,
  points: 534,
  gpEntries: 211 ,
  worldChampionships: 0,
  highestRaceFinish:"4 (x3)",
  highestGridPosition: 1 ,
  dateOfBirth: "19/08/1987" ,
  placeOfBirth: "Emmerich am Rhein, Germany" 
  },
  {imgsrc: 'assets/driver-info/MAG.avif', 
  number: 20, 
  nationality: 'assets/countries/denmark-flag.avif',
  name: "Kevin Magnussen", 
  team: "Haas",
  country: "Denmark",
  podiums: 1,
  points: 187,
  gpEntries: 169,
  worldChampionships: 0,
  highestRaceFinish:"2 (x1)",
  highestGridPosition: 4 ,
  dateOfBirth: "05/10/1992" ,
  placeOfBirth: "Roskilde, Denmark" 
  },
  {imgsrc: 'assets/driver-info/ALB.avif', 
  number: 23, 
  nationality: 'assets/countries/thailand-flag.png',
  name: "Alexander Albon", 
  team: "Williams",
  country: "Thailand",
  podiums: 2,
  points: 228,
  gpEntries: 86 ,
  worldChampionships: 0,
  highestRaceFinish:"3 (x2)",
  highestGridPosition: 4 ,
  dateOfBirth: "23/03/1996" ,
  placeOfBirth: "London, England" 
  },
  {imgsrc: 'assets/driver-info/SAR.avif', 
  number: 2, 
  nationality: 'assets/countries/united-states-flag.avif',
  name: "Logan Sargeant", 
  team: "Williams",
  country: "USA",
  podiums: 0,
  points: 1,
  gpEntries: 26 ,
  worldChampionships: 0,
  highestRaceFinish:"10 (x1)",
  highestGridPosition: 6 ,
  dateOfBirth: "31/12/2000" ,
  placeOfBirth: "Fort Lauderdale, Florida" 
  },
  {imgsrc: 'assets/driver-info/BOT.avif', 
  number: 77, 
  nationality: 'assets/countries/finland-flag.avif',
  name: "Valtteri Bottas", 
  team: "Sauber",
  country: "Finland",
  podiums: 67,
  points: 1797,
  gpEntries: 227 ,
  worldChampionships: 0,
  highestRaceFinish:"1 (x10)",
  highestGridPosition: 1 ,
  dateOfBirth: "28/08/1989" ,
  placeOfBirth: "Nastola, Finland" 
  },
  {imgsrc: 'assets/driver-info/ZHO.avif', 
  number: 24, 
  nationality: 'assets/countries/china-flag.avif',
  name: "Zhou Guanyu", 
  team: "Sauber",
  country: "China",
  podiums: 0,
  points: 12,
  gpEntries: 49 ,
  worldChampionships: 0,
  highestRaceFinish:"8 (x1)",
  highestGridPosition: 1 ,
  dateOfBirth: "30/05/1999" ,
  placeOfBirth: "Shanghai, China" 
  },
  {imgsrc: 'assets/driver-info/OCO.avif', 
  number: 31, 
  nationality: 'assets/countries/france-flag.avif',
  name: "Esteban Ocon", 
  team: "Alpine",
  country: "France",
  podiums: 3,
  points: 422,
  gpEntries: 138 ,
  worldChampionships: 0,
  highestRaceFinish:"1 (x1)",
  highestGridPosition: 3 ,
  dateOfBirth: "17/09/1996" ,
  placeOfBirth: "Évreux, Normandy" 
  },
  {imgsrc: 'assets/driver-info/GAS.avif', 
  number: 10, 
  nationality: 'assets/countries/france-flag.avif',
  name: "Pierre Gasly", 
  team: "Alpine",
  country: "France",
  podiums: 4,
  points: 394,
  gpEntries: 135 ,
  worldChampionships: 0,
  highestRaceFinish:"1 (x1)",
  highestGridPosition: 1 ,
  dateOfBirth: "07/02/1996" ,
  placeOfBirth: "Rouen, France" 
  },

]

@Component({
  selector: 'app-driver-info',
  templateUrl: './driver-info.component.html',
  styleUrl: './driver-info.component.scss'
})
export class DriverInfoComponent implements OnInit {
  constructor(private activateRoute: ActivatedRoute){

  }
  index = 1;
  driver = drivers[1];
  ngOnInit(): void {
      this.activateRoute.params.subscribe((param) => {
        this.index = param['id'];
        this.driver = drivers[this.index];
      })
  }

  
}
